apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        command:
        - /bin/bash
        - -c
        - |
          echo "0 3 * * 1 cp /config/Backups/scheduled/* /downloads/Backups/" | crontab - &&           service cron start &&           exec /init
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config-pvc
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc
