apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: NodePort
  ports:
    - port: 8989
      targetPort: 8989
      nodePort: 30889
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: sonarr
