image:
  repository: linuxserver/tautulli
  tag: latest
  pullPolicy: IfNotPresent

env:
  PUID: 1000
  PGID: 100
  TZ: Europe/Berlin

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        port: 8181
        nodePort: 30881  # You can change this if needed

persistence:
  config:
    enabled: true
    storageClass: longhorn-2replicas
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /config

resources: {}
nodeSelector:
  kubernetes.io/hostname: node1

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 100
