image:
  repository: linuxserver/tautulli
  tag: latest
  pullPolicy: IfNotPresent

env:
  PUID: 1000
  PGID: 100
  TZ: Europe/Berlin

service:
  type: NodePort
  port: 8181
  nodePort: 30881

persistence:
  enabled: true
  storageClass: longhorn-2replicas
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /config

nodeSelector:
  kubernetes.io/hostname: node1

securityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 100
