apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:flint24/k8s-apps.git'
    targetRevision: main
    path: overseerr
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
