apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: overseerr
  ports:
    - port: 5055
      targetPort: 5055
      nodePort: 31055
      protocol: TCP
