image:
  repository: ghcr.io/sct/overseerr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5055
  nodePort: 30893

persistence:
  config:
    enabled: true
    storageClass: longhorn-2replicas
    size: 5Gi
    mountPath: /app/config
