image:
  repository: ghcr.io/linuxserver/overseerr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5055

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/overseerr/config
    mountPath: /config

resources: {}
nodeSelector:
  kubernetes.io/hostname: node1
