image:
  repository: linuxserver/overseerr
  tag: latest

service:
  main:
    type: NodePort
    ports:
      http: 5055
    nodePort: 30893

persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: overseerr-config

env:
  TZ: UTC
