image:
  repository: ghcr.io/linuxserver/overseerr
  tag: 1.33.2 # Or latest
  pullPolicy: IfNotPresent

service:
  main:
    type: NodePort
    ports:
      http:
        port: 5055
        nodePort: 31055

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/overseerr
    mountPath: /config

env:
  TZ: Europe/London
  LOG_LEVEL: info
