apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bazarr
  namespace: argocd
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bazarr
    repoURL: https://github.com/flint24/k8s-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
