apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"immich","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"server","app.kubernetes.io/version":"v1.119.0","helm.sh/chart":"immich-0.9.2"},"name":"immich-server","namespace":"immich"},"spec":{"replicas":1,"revisionHistoryLimit":3,"selector":{"matchLabels":{"app.kubernetes.io/instance":"immich","app.kubernetes.io/name":"server"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"immich","app.kubernetes.io/name":"server"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["node1"]}]}]}}},"automountServiceAccountToken":true,"containers":[{"env":[{"name":"DB_DATABASE_NAME","value":"immich"},{"name":"DB_HOSTNAME","value":"immich-postgresql.immich.svc.cluster.local"},{"name":"DB_PASSWORD","value":"u9FNA6p6D9"},{"name":"DB_PORT","value":"5432"},{"name":"DB_USERNAME","value":"postgres"},{"name":"IMMICH_SERVER_HOST","value":"0.0.0.0"},{"name":"IMMICH_SERVER_PORT","value":"3001"},{"name":"NODE_ENV","value":"production"},{"name":"REDIS_HOSTNAME","value":"immich-redis-master"},{"name":"REDIS_PASSWORD","value":"zGltO4nlXp"}],"image":"ghcr.io/immich-app/immich-server:v1.119.0","imagePullPolicy":null,"livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/server/ping","port":"http"},"initialDelaySeconds":0,"periodSeconds":10,"timeoutSeconds":1},"name":"immich-server","ports":[{"containerPort":3001,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/server/ping","port":"http"},"initialDelaySeconds":0,"periodSeconds":10,"timeoutSeconds":1},"startupProbe":{"failureThreshold":30,"httpGet":{"path":"/api/server/ping","port":"http"},"initialDelaySeconds":0,"periodSeconds":10,"timeoutSeconds":1},"volumeMounts":[{"mountPath":"/usr/src/app/upload","name":"library"}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"serviceAccountName":"default","volumes":[{"name":"library","persistentVolumeClaim":{"claimName":"dummy-claim"}}]}}}}
    meta.helm.sh/release-name: immich
    meta.helm.sh/release-namespace: immich
  creationTimestamp: "2025-04-07T07:54:28Z"
  generation: 15
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: server
    app.kubernetes.io/version: v1.119.0
    helm.sh/chart: immich-0.9.2
  name: immich-server
  namespace: immich
  resourceVersion: "879296"
  uid: 2f36b28e-e199-4193-8df1-950bf9eca912
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-04-07T17:39:42+01:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: immich
        app.kubernetes.io/name: server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1
      automountServiceAccountToken: true
      containers:
      - env:
        - name: DB_DATABASE_NAME
          value: immich
        - name: DB_HOSTNAME
          value: immich-postgresql.immich.svc.cluster.local
        - name: DB_PASSWORD
          value: u9FNA6p6D9
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: postgres
        - name: IMMICH_SERVER_HOST
          value: 0.0.0.0
        - name: IMMICH_SERVER_PORT
          value: "3001"
        - name: NODE_ENV
          value: production
        - name: REDIS_HOSTNAME
          value: immich-redis-master
        - name: REDIS_PASSWORD
          value: zGltO4nlXp
        image: ghcr.io/immich-app/immich-server:v1.119.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/server/ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: immich-server
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/server/ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /api/server/ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/src/app/upload
          name: library
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: library
        persistentVolumeClaim:
          claimName: immich-new-claim
status:
  conditions:
  - lastTransitionTime: "2025-04-07T18:16:29Z"
    lastUpdateTime: "2025-04-07T18:16:29Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-04-07T17:36:45Z"
    lastUpdateTime: "2025-04-07T18:27:51Z"
    message: ReplicaSet "immich-server-76746799c9" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 15
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
