apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-new-claim
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: longhorn-2replicas
