apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: overseerr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: overseerr
    spec:
      containers:
        - name: overseerr
          image: ghcr.io/sct/overseerr:latest
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: TZ
              value: Europe/Berlin
      volumes:
        - name: config
          hostPath:
            path: /mnt/Father/downloads/overseerr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: overseerr
  ports:
    - port: 5055
      targetPort: 5055
      nodePort: 30893
