---
# Source: tautulli/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  labels:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/version: latest
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: tautulli
    app.kubernetes.io/part-of: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2replicas
---
# Source: tautulli/charts/tautulli/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/version: v2.7.7
    helm.sh/chart: tautulli-11.4.2
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8181
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
---
# Source: tautulli/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/version: latest
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: tautulli
    app.kubernetes.io/part-of: media-stack
spec:
  type: NodePort
  ports:
    - name: http
      port: 8181
      targetPort: http
      nodePort: 30881
  selector:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
---
# Source: tautulli/charts/tautulli/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/version: v2.7.7
    helm.sh/chart: tautulli-11.4.2
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/instance: tautulli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
        app.kubernetes.io/instance: tautulli
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: tautulli
          image: "ghcr.io/k8s-at-home/tautulli:v2.7.7"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: UTC
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
---
# Source: tautulli/templates/deployment.yaml
# File: tautulli/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/name: tautulli
    helm.sh/chart: tautulli-0.1.0
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/instance: tautulli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
        app.kubernetes.io/instance: tautulli
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      securityContext:
        fsGroup: 100
      containers:
        - name: tautulli
          image: linuxserver/tautulli:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tautulli-config
