apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  destination:
    namespace: velero
    server: https://kubernetes.default.svc
  project: default
  source:
    path: velero
    repoURL: https://github.com/flint24/k8s-apps.git
    targetRevision: main
    helm:
      skipCrds: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
