apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: readarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: readarr
    spec:
      containers:
        - name: readarr
          image: linuxserver/readarr:0.4.14-nightly
          ports:
            - containerPort: 8787
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Berlin
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: readarr-config
        - name: downloads
          hostPath:
            path: /mnt/Father/downloads/readarr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-2replicas
---
apiVersion: v1
kind: Service
metadata:
  name: readarr
  namespace: media
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: readarr
  ports:
    - port: 8787
      targetPort: 8787
      nodePort: 30887
