apiVersion: v1
kind: Service
metadata:
  name: readarr
  namespace: media
  labels:
    app.kubernetes.io/name: readarr
    app.kubernetes.io/instance: readarr
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: readarr
    app.kubernetes.io/instance: readarr
  ports:
    - name: http
      port: 8787
      targetPort: 8787
      nodePort: 31878
