image:
  repository: linuxserver/readarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: "Europe/Berlin"
  PUID: 1000
  PGID: 1000

service:
  main:
    type: NodePort
    ports:
      http:
        port: 8787

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/readarr/config
    mountPath: /config
  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/readarr
    mountPath: /downloads
