image:
  repository: ghcr.io/linuxserver/readarr:develop
  tag: 0.3.27-develop
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 7878
  nodePort: 31788

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/readarr/config
  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/readarr
