image:
  repository: lscr.io/linuxserver/readarr
  tag: 0.3.19.2413-ls193
  pullPolicy: IfNotPresent

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        port: 8787
        nodePort: 31789

persistence:
  config:
    enabled: true
    type: hostPath
    mountPath: /config
    hostPath: /mnt/Father/downloads/readarr/config

  data:
    enabled: true
    type: hostPath
    mountPath: /data
    hostPath: /mnt/Father/downloads/readarr
