image:
  repository: linuxserver/readarr
  tag: 0.4.14-nightly
  pullPolicy: IfNotPresent

env:
  TZ: "UTC"
  PUID: 1000
  PGID: 1000

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/readarr/config
    mountPath: /config
  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/readarr
    mountPath: /data

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        port: 8787

resources: {}
nodeSelector:
  kubernetes.io/hostname: node1
