apiVersion: v1
kind: Service
metadata:
  name: stubby
spec:
  type: NodePort
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30530
    - port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30530
