apiVersion: v2
name: prowlarr
description: A lightweight wrapper for bjw-s/app-template
type: application
version: 1.0.0
appVersion: "1.14.0"
dependencies:
  - name: app-template
    version: 2.6.0
    repository: https://bjw-s.github.io/helm-charts
