apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: "ghcr.io/linuxserver/prowlarr:latest"
          ports:
            - containerPort: 9696
              name: http
          volumeMounts:
            - name: downloads
              mountPath: /mnt/Father/downloads/prowlarr
            - name: config
              mountPath: /config
      volumes:
        - name: downloads
          hostPath:
            path: /mnt/Father/downloads/prowlarr
            type: Directory
        - name: config
          hostPath:
            path: /mnt/Father/downloads/prowlarr/config
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  type: NodePort
  ports:
    - port: 9696
      nodePort: 31000
      protocol: TCP
  selector:
    app: prowlarr

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  source:
    repoURL: "git@github.com:<your-github-repo>"
    targetRevision: HEAD
    path: k8s-apps/prowlarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
