image:
  repository: ghcr.io/bjw-s/prowlarr
  tag: v1.12.3.4056
  pullPolicy: IfNotPresent

env:
  TZ: America/New_York

service:
  main:
    ports:
      http:
        port: 9696

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr/config
    mountPath: /config

  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr
    mountPath: /data

resources: {}
