controller:
  type: deployment

image:
  repository: linuxserver/prowlarr
  tag: 1.14.0

env:
  TZ: Europe/Berlin

service:
  main:
    enabled: true
    controller: main
    ports:
      http:
        port: 9696
    type: NodePort

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr/config
  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr
