global:
  nameOverride: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr

app-template:
  serviceAccount:
    create: true

  controllers:
    main:
      containers:
        main:
          image:
            repository: linuxserver/prowlarr
            tag: "latest"
          env:
            TZ: "Europe/Berlin"
          resources: {}

  service:
    main:
      controller: main
      ports:
        http:
          port: 9696
      type: NodePort
      nodePort: 31000

  persistence:
    config:
      enabled: true
      type: hostPath
      hostPath: /mnt/Father/downloads/prowlarr/config
      globalMounts:
        - path: /config
    data:
      enabled: true
      type: hostPath
      hostPath: /mnt/Father/downloads/prowlarr
      globalMounts:
        - path: /data

  nodeSelector:
    kubernetes.io/hostname: node1
