image:
  repository: linuxserver/prowlarr
  tag: develop

env:
  TZ: "Europe/Berlin"

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        enabled: true
        port: 9696
        nodePort: 30996

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr/config
    mountPath: /config
  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr
    mountPath: /data

nodeSelector:
  kubernetes.io/hostname: node1

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
