controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/prowlarr
          tag: 1.14.0
        env:
          TZ: Europe/Berlin
        resources: {}

service:
  main:
    controller: main
    ports:
      http:
        port: 9696
    type: NodePort

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr/config
    globalMounts:
      - path: /config
  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr
    globalMounts:
      - path: /data
