image:
  repository: linuxserver/prowlarr
  tag: version-1.25.4.4818
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9696
  nodePort: 30894

persistence:
  config:
    enabled: true
    storageClass: longhorn-2replicas
    size: 5Gi
  downloads:
    path: /mnt/Father/downloads/prowlarr
  watch:
    path: /mnt/Father/downloads/prowlarr/watch

resources: {}
