image:
  repository: ghcr.io/linuxserver/prowlarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9696
  nodePort: 30996

persistence:
  config:
    enabled: true
    existingClaim: prowlarr-config
  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr
  watch:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr/watch

resources: {}
