image:
  repository: linuxserver/prowlarr
  tag: version-1.25.4.4818
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9696
  nodePort: 30894

persistence:
  config:
    enabled: true
    existingClaim: prowlarr-config
  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr
  watch:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/prowlarr/watch

env:
  TZ: UTC
