apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: "linuxserver/sabnzbd:4.2.2"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TZ
        - name: SABNZBD_HOST_WHITELIST_ENTRIES
          value: "*"
              value: Europe/Berlin
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "000"
            - name: CONFIG_FILE
              value: /config/sabnzbd.ini
            - name: HOST_WHITELIST
              value: "*"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config
        - name: data
          hostPath:
            path: /mnt/Father/downloads/sabnzbd
        - name: downloads
          hostPath:
            path: /mnt/Father/downloads/sabnzbd
