apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30888
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: sabnzbd
