immich:
  metrics:
    enabled: false

  persistence:
    library:
      enabled: false
      existingClaim: "dummy-claim"  # Required by the Helm chart; not actually used

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0

  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001

  env:
    DB_PORT: 5432
    DB_USERNAME: postgres              # Match the default from immich-postgresql chart
    DB_PASSWORD: u9FNA6p6D9              # Match the default from immich-postgresql chart
    DB_DATABASE_NAME: immich
    DB_HOSTNAME: immich-postgresql.immich.svc.cluster.local
    REDIS_HOSTNAME: immich-redis-master
    IMMICH_MACHINE_LEARNING_URL: http://immich-ml:3003
    NODE_ENV: production

  startupProbe:
    httpGet:
      path: /api/server/ping
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 30

  volumeMounts:
    - name: pics
      mountPath: /usr/src/app/upload

machine-learning:
  enabled: false

volumes:
  - name: pics
    hostPath:
      path: /mnt/Father/Pics
      type: Directory
