immich:
  metrics:
    enabled: false

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001
  env:
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD: u9FNA6p6D9
    DB_DATABASE_NAME: immich
    DB_HOSTNAME: immich-postgresql.immich.svc.cluster.local
    REDIS_HOSTNAME: immich-redis-master
    REDIS_PASSWORD: zGltO4nlXp
    NODE_ENV: production
  volumeMounts:
    - name: pics
      mountPath: /usr/src/app/upload

microservices:
  enabled: true
  env:
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD: u9FNA6p6D9
    DB_DATABASE_NAME: immich
    DB_HOSTNAME: immich-postgresql.immich.svc.cluster.local
    REDIS_HOSTNAME: immich-redis-master
    REDIS_PASSWORD: zGltO4nlXp
    NODE_ENV: production

machine-learning:
  enabled: false

postgresql:
  enabled: false

redis:
  enabled: false
  auth:
    enabled: true
    password: zGltO4nlXp

volumes:
  - name: pics
    hostPath:
      path: /mnt/Father/Pics
      type: Directory

immich:
  persistence:
    library:
      enabled: false
