immich:
  persistence:
    library:
      enabled: true
      type: hostPath
      hostPath: /mnt/Father/Pics
      mountPath: /usr/src/app/upload

  metrics:
    enabled: false

  configuration: {}
    # Example if needed:
    # trash:
    #   enabled: false
    #   days: 30

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
    pullPolicy: IfNotPresent

  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001

machine-learning:
  enabled: false

postgresql:
  enabled: false

redis:
  enabled: false
