immich:
  metrics:
    enabled: false

  persistence:
    library:
      enabled: false
      existingClaim: "dummy-claim"  # Required by the Helm chart; not actually used

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001

  volumeMounts:
    - name: pics
      mountPath: /usr/src/app/upload

machine-learning:
  enabled: false

volumes:
  - name: pics
    hostPath:
      path: /mnt/Father/Pics
      type: Directory
