immich:
  metrics:
    enabled: false
  env:
    DB_PORT: 5432
    DB_USERNAME: immich
    DB_PASSWORD: immichpass
    DB_DATABASE_NAME: immich
    REDIS_HOSTNAME: immich-redis
    IMMICH_MACHINE_LEARNING_URL: http://immich-ml:3003
    NODE_ENV: production
    DB_HOSTNAME: immich-postgresql.immich.svc.cluster.local

  persistence:
    library:
      enabled: false
      existingClaim: "dummy-claim"  # Required by the Helm chart; not actually used

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001

  startupProbe:
    httpGet:
      path: /api/server/ping
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 30  # <-- was probably much lower before

  volumeMounts:
    - name: pics
      mountPath: /usr/src/app/upload

machine-learning:
  enabled: false

volumes:
  - name: pics
    hostPath:
      path: /mnt/Father/Pics
      type: Directory
