immich:
  metrics:
    enabled: false
  persistence:
    library:
      enabled: false
      existingClaim: "dummy-claim"

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
  env:
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD: RN3YhUS9U7S
    DB_DATABASE_NAME: immich
    DB_HOSTNAME: immich-postgresql.immich.svc.cluster.local
    REDIS_HOSTNAME: immich-redis-master
    IMMICH_MACHINE_LEARNING_URL: http://immich-ml:3003
    NODE_ENV: production
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001
  startupProbe:
    httpGet:
      path: /api/server/ping
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 30
  volumeMounts:
    - name: pics
      mountPath: /usr/src/app/upload

microservices:
  enabled: true
  env:
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD: RN3YhUS9U7S
    DB_DATABASE_NAME: immich
    DB_HOSTNAME: immich-postgresql.immich.svc.cluster.local
    REDIS_HOSTNAME: immich-redis-master
    IMMICH_MACHINE_LEARNING_URL: http://immich-ml:3003
    NODE_ENV: production

machine-learning:
  enabled: false

volumes:
  - name: pics
    hostPath:
      path: /mnt/Father/Pics
      type: Directory
