immich:
  persistence: {}
  metrics:
    enabled: false
  configuration:
    storageTemplate:
      enabled: true
      template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
    trash:
      enabled: false

machine-learning:
  enabled: false

postgresql:
  enabled: false

redis:
  enabled: false

server:
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001

microservices:
  enabled: true

persistence:
  library:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/Pics
    accessMode: ReadWriteOnce
    size: 500Gi
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - node1
