immich:
  metrics:
    enabled: false
  persistence:
    library:
      enabled: false
      existingClaim: "dummy-claim"

postgresql:
  enabled: false

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
  env:
    - name: DB_PORT
      value: "5432"
    - name: DB_USERNAME
      value: "postgres"
    - name: DB_PASSWORD
      value: "fYCcHNZtHM"
    - name: DB_DATABASE_NAME
      value: "immich"
    - name: DB_HOSTNAME
      value: "my-postgres-postgresql.immich.svc.cluster.local"
    - name: REDIS_HOSTNAME
      value: "immich-redis-master"
    - name: IMMICH_MACHINE_LEARNING_URL
      value: "http://immich-ml:3003"
    - name: NODE_ENV
      value: "production"
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001
  startupProbe:
    httpGet:
      path: /api/server/ping
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 30
  volumeMounts:
    - name: pics
      mountPath: /usr/src/app/upload

microservices:
  enabled: true
  env:
    - name: DB_PORT
      value: "5432"
    - name: DB_USERNAME
      value: "postgres"
    - name: DB_PASSWORD
      value: "fYCcHNZtHM"
    - name: DB_DATABASE_NAME
      value: "immich"
    - name: DB_HOSTNAME
      value: "my-postgres-postgresql.immich.svc.cluster.local"
    - name: REDIS_HOSTNAME
      value: "immich-redis-master"
    - name: IMMICH_MACHINE_LEARNING_URL
      value: "http://immich-ml:3003"
    - name: NODE_ENV
      value: "production"

machine-learning:
  enabled: false

redis:
  enabled: true
  auth:
    enabled: false

volumes:
  - name: pics
    hostPath:
      path: /mnt/Father/Pics
      type: Directory
