apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
    spec:
      containers:
        - name: tautulli
          image: "linuxserver/tautulli:latest"
          ports:
            - containerPort: 8181
              name: http
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tautulli-config
