apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: media
  labels:
    app.kubernetes.io/name: tautulli
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: tautulli
  ports:
    - name: http
      port: 8181
      targetPort: 8181
      nodePort: 30881
      protocol: TCP
