image:
  repository: linuxserver/readeck
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30987  # <-- new NodePort (free)

persistence:
  config:
    enabled: true
    storageClass: longhorn-2replicas
    size: 5Gi
  downloads:
    path: /mnt/Father/downloads/readeck

resources: {}
