image:
  repository: localhost/readeck-arm64
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30897

persistence:
  enabled: false

resources: {}
