apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: downloads
  labels:
    app: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: linuxserver/sabnzbd:latest
          ports:
            - containerPort: 8080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: sabnzbd-downloads
              mountPath: /downloads
      volumes:
        - name: sabnzbd-config
          hostPath:
            path: /mnt/Father/downloads/sabnzbd/config
            type: DirectoryOrCreate
        - name: sabnzbd-downloads
          hostPath:
            path: /mnt/Father/downloads/sabnzbd
            type: Directory
