apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  type: NodePort
  selector:
    app: sabnzbd
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32080
