apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-nodeport
  namespace: media
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sabnzbd
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30888
