kimage:
  repository: linuxserver/sabnzbd
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    type: NodePort
    ports:
      http:
        port: 8080

persistence:
  config:
    enabled: true
    type: hostPath
    mountPath: /config
    hostPath: /mnt/Father/downloads/sabnzbd
