image:
  repository: ghcr.io/k8s-at-home/sabnzbd
  tag: v3.3.1

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/sabnzbd/config
    mountPath: /config

service:
  main:
    type: NodePort
    ports:
      http:
        port: 8080

env:
  TZ: "UTC"

ingress:
  main:
    enabled: false

resources: {}
