env:
  CONFIG_FILE: /config/sabnzbd.ini
  HOST_WHITELIST: "*"
  PGID: 1000
  PUID: 1000
  TZ: Europe/London
  UMASK: "000"

image:
  repository: linuxserver/sabnzbd
  tag: 4.2.2
  pullPolicy: IfNotPresent

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    hosts:
      - host: sabnzbd.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/local-volumes/sabnzbd/config
    mountPath: /config

  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/sabnzbd
    mountPath: /data

  downloads:
    enabled: false
    mountPath: /downloads

  media:
    enabled: false
    mountPath: /media

securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsUser: 1000

probes:
  startup:
    enabled: true
    path: /
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 20
