image:
  repository: linuxserver/sabnzbd
  tag: 4.2.2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30888

env:
  SABNZBD__HOST_WHITELIST_ENTRIES: "*"
  TZ: Europe/Berlin

persistence:
  config:
    enabled: true
    storageClass: longhorn-2replicas
    size: 5Gi
  data:
    path: /mnt/Father/downloads/sabnzbd

resources: {}
