image:
  repository: ghcr.io/linuxserver/sabnzbd
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    type: NodePort
    ports:
      http:
        port: 8080
        nodePort: 32573

env:
  TZ: Europe/Berlin
  PUID: 1000
  PGID: 1000
  HOST_WHITELIST: "*,node4"

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/sabnzbd/config
    mountPath: /config
