image:
  repository: linuxserver/sabnzbd
  tag: 4.2.2
  pullPolicy: IfNotPresent

env:
  TZ: Europe/London
  PUID: 1000
  PGID: 1000

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        port: 8080
        nodePort: 30888

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/sabnzbd/config
    mountPath: /config

  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/sabnzbd
    mountPath: /downloads

ingress:
  main:
    enabled: false

resources: {}
