apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
  labels:
    app.kubernetes.io/name: radarr
spec:
  type: NodePort
  ports:
    - port: 7878
      targetPort: 7878
      nodePort: 30788
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: radarr
