apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: overseerr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: overseerr
    spec:
      containers:
        - name: overseerr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: TZ
              value: Europe/Berlin
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: overseerr-config
