apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
