apiVersion: v1
kind: Service
metadata:
  name: overseerr
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: overseerr
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5055
      nodePort: {{ .Values.service.nodePort }}
