apiVersion: v1
kind: Service
metadata:
  name: overseerr
spec:
  type: NodePort
  ports:
    - port: 5055
      targetPort: 5055
      nodePort: 30893
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: overseerr
