apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lidarr
    spec:
      containers:
        - name: lidarr
          image: "linuxserver/lidarr:latest"
          ports:
            - containerPort: 8686
              name: http
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: music
              mountPath: /music
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: downloads
          hostPath:
            path: /mnt/Father/downloads/lidarr
        - name: music
          hostPath:
            path: /mnt/Father/Music
