apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lidarr.fullname" . }}
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lidarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lidarr.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      securityContext:
        fsGroup: 100
      containers:
        - name: lidarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
          ports:
            - containerPort: 8686
          volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            - name: downloads
              mountPath: {{ .Values.persistence.downloads.mountPath }}
            - name: music
              mountPath: {{ .Values.persistence.music.mountPath }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "lidarr.fullname" . }}-config
        - name: downloads
          hostPath:
            path: {{ .Values.persistence.downloads.hostPath }}
        - name: music
          hostPath:
            path: {{ .Values.persistence.music.hostPath }}
