apiVersion: v1
kind: Service
metadata:
  name: lidarr
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: lidarr
  ports:
    - port: 8686
      targetPort: 8686
      protocol: TCP
      nodePort: 30886
