apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 20.12.1
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: true
            storageClass: longhorn-2replicas
            size: 2Gi
            accessModes:
              - ReadWriteOnce
        replica:
          replicaCount: 0
        service:
          type: ClusterIP
          port: 6379
        image:
          tag: 7.2.4-debian-11-r0
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
