architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: true
    storageClass: longhorn-2replicas
    size: 2Gi
    accessModes:
      - ReadWriteOnce

replica:
  replicaCount: 0

service:
  type: ClusterIP
  port: 6379
