redis:
  enabled: false

env:
  REDIS_HOSTNAME: immich-redis.media.svc.cluster.local
  REDIS_PORT: 6379

ingress:
  enabled: false

# Use Longhorn for config
persistence:
  config:
    enabled: true
    existingClaim: immich-config

# Use hostPath for photos
immich:
  server:
    volumes:
      - name: photos
        hostPath:
          path: /mnt/Father/Pics
    volumeMounts:
      - mountPath: /usr/src/app/upload
        name: photos

ml:
  enabled: false
