image:
  repository: 
  tag: 
  pullPolicy: IfNotPresent

env:
  PUID: 1000
  PGID: 100
  TZ: Europe/Berlin

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        port: 80
        nodePort: 30

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 
    accessMode: ReadWriteOnce
    storageClass: 

  data:
    enabled: true
    type: hostPath
    hostPath: /nextcloud
    mountPath: /data

resources: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 100

nodeSelector:
  kubernetes.io/hostname: node1
