image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 7878
  nodePort: 30788

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/radarr/config

resources: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
