image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 7878
  nodePort: 30788

persistence:
  config:
    enabled: true
    size: 5Gi
    storageClass: longhorn-2replicas
    accessMode: ReadWriteOnce

resources: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Remove node pinning
affinity: {}
nodeSelector: {}
tolerations: []

# Disable probes temporarily to prevent crash loops
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
