image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8787
  nodePort: 30788

persistence:
  config:
    enabled: true
    size: 5Gi
    storageClass: longhorn-2replicas
    accessMode: ReadWriteOnce

resources: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 1000

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
