image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 7878
  nodePort: 30788

persistence:
  config:
    enabled: true
    size: 5Gi
    storageClass: longhorn-2replicas
    accessMode: ReadWriteOnce

resources: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

affinity: {}
nodeSelector: {}
tolerations: []

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
