apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      securityContext:
        fsGroup: 100
      containers:
        - name: immich
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: DB_URL
              value: "{{ .Values.env.DB_URL }}"
            - name: REDIS_HOSTNAME
              value: "{{ .Values.env.REDIS_HOSTNAME }}"
            - name: REDIS_PORT
              value: "{{ .Values.env.REDIS_PORT }}"
            - name: IMMICH_MACHINE_LEARNING_URL
              value: "{{ .Values.env.IMMICH_MACHINE_LEARNING_URL }}"
            - name: IMMICH_ENABLE_MACHINE_LEARNING
              value: "{{ .Values.env.IMMICH_ENABLE_MACHINE_LEARNING }}"
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: uploads
              mountPath: /usr/src/app/upload
            - name: backups
              mountPath: /backups
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: immich-config
        - name: uploads
          hostPath:
            path: /mnt/Father/Pics
        - name: backups
          hostPath:
            path: /mnt/Father/downloads/Backups/immich
