apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2replicas
