apiVersion: v1
kind: Service
metadata:
  name: immich
  labels:
    app: immich
spec:
  type: NodePort
  selector:
    app: immich
  ports:
    - port: 2283
      targetPort: 3001
      nodePort: 31283
      protocol: TCP
