apiVersion: v1
kind: Service
metadata:
  name: immich
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: immich
  ports:
    - name: http
      port: 3001
      targetPort: http
      nodePort: 30001
