apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-claim
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  volumeMode: Filesystem
  storageClassName: longhorn
