postgresql:
  auth:
    postgresPassword: fYCcHNZtHM
    database: immich

  primary:
    persistence:
      enabled: true
      size: 8Gi
    service:
      type: ClusterIP

fullnameOverride: immich-postgresql
