global:
  security:
    allowInsecureImages: true

image:
  repository: pgvector/pgvector
  tag: latest
  pullPolicy: IfNotPresent

auth:
  enablePostgresUser: true
  postgresPassword: u9FNA6p6D9
  username: postgres
  password: u9FNA6p6D9
  database: immich

primary:
  nameOverride: immich-postgresql
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
