auth:
  username: postgres
  password: u9FNA6p6D9
  database: immich

volumePermissions:
  enabled: true

image:
  repository: bitnami/postgresql
  tag: 16.3.0-debian-12-r10

  persistence:
    enabled: true
    storageClass: longhorn-2replicas
    size: 8Gi
