apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  source:
    repoURL: https://github.com/your-username/your-k8s-gitops-repo
    targetRevision: HEAD
    path: immich/immich  # This should be the folder containing the Immich Helm chart
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
