immich:
  configuration: {}
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-pvc

postgresql:
  enabled: false

redis:
  enabled: false

machine-learning:
  enabled: false

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 2283
