# immich/values.yaml

image:
  repository: ghcr.io/immich-app/immich-server
  tag: v1.103.1
  pullPolicy: IfNotPresent

env:
  DB_DATABASE_NAME: postgres
  DB_HOSTNAME: my-app-postgresql.default.svc.cluster.local
  DB_PASSWORD: 5p8EFuAZuc
  DB_PORT: 5432
  DB_USERNAME: postgres
  IMMICH_ENABLE_MACHINE_LEARNING: false
  IMMICH_MACHINE_LEARNING_URL: http://127.0.0.1:3003
  PGID: 100
  PUID: 1000
  TZ: Europe/Berlin

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        port: 3001
        nodePort: 3001

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: longhorn-2replicas

  uploads:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/Pics
    mountPath: /usr/src/app/upload

  backups:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/Backups/immich
    mountPath: /backups

resources: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 100
