image:
  repository: ghcr.io/immich-app/immich-server
  tag: v1.104.0
  pullPolicy: IfNotPresent

env:
  PUID: 1000
  PGID: 100
  TZ: Europe/Berlin

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        port: 3001
        nodePort: 30001

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: longhorn-2replicas

  uploads:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/Pics
    mountPath: /usr/src/app/upload

  backups:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/Backups/immich
    mountPath: /backups

resources: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 100

nodeSelector:
  kubernetes.io/hostname: node1
