immich:
  persistence:
    library:
      type: hostPath
      hostPath: /mnt/Father/Pics
  metrics:
    enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        password: immich

redis:
  enabled: true

machine-learning:
  enabled: false

server:
  nodeSelector:
    kubernetes.io/hostname: node1
  service:
    main:
      type: NodePort
