immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-pvc
  configuration:
    trash:
      enabled: true
      days: 30
    storageTemplate:
      enabled: true
      template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: v1.119.0
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false
  service:
    main:
      type: NodePort
      ports:
        http:
          port: 3001

machine-learning:
  enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        password: immich
  primary:
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;

redis:
  enabled: true
  auth:
    enabled: false
