apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: config
              mountPath: /config
{{- if .Values.persistence.downloads.enabled }}
            - name: downloads
              mountPath: /downloads
{{- end }}
{{- if .Values.persistence.watch.enabled }}
            - name: watch
              mountPath: /watch
{{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
{{- if .Values.persistence.downloads.enabled }}
        - name: downloads
          hostPath:
            path: {{ .Values.persistence.downloads.hostPath }}
{{- end }}
{{- if .Values.persistence.watch.enabled }}
        - name: watch
          hostPath:
            path: {{ .Values.persistence.watch.hostPath }}
{{- end }}
