apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 9696
          env:
            - name: TZ
              value: UTC
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: watch
              mountPath: /watch
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: downloads
          hostPath:
            path: "{{ .Values.persistence.downloads.path }}"
            type: DirectoryOrCreate
        - name: watch
          hostPath:
            path: "{{ .Values.persistence.watch.path }}"
            type: DirectoryOrCreate
