apiVersion: v1
kind: Service
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.main.type }}
  selector:
    {{- include "prowlarr.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.main.ports.http.port }}
      targetPort: http
      nodePort: {{ .Values.service.main.ports.http.nodePort }}
