apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prowlarr
  ports:
    - port: 9696
      targetPort: 9696
      nodePort: 30996
