apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9696
      nodePort: {{ .Values.service.nodePort | int }}
  selector:
    app.kubernetes.io/name: prowlarr
