apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bazarr
    spec:
      containers:
        - name: bazarr
          image: "linuxserver/bazarr:latest"
          ports:
            - containerPort: 6767
              name: http
          env:
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: movies1
              mountPath: /movies/father
            - name: movies2
              mountPath: /movies/mother
            - name: tv1
              mountPath: /tv/father
            - name: tv2
              mountPath: /tv/mother
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: movies1
          hostPath:
            path: /mnt/Father/Movies
        - name: movies2
          hostPath:
            path: /mnt/Mother/Movies
        - name: tv1
          hostPath:
            path: /mnt/Father/TV
        - name: tv2
          hostPath:
            path: /mnt/Mother/TV
