apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  type: NodePort
  ports:
    - port: 6767
      targetPort: 6767
      nodePort: 30892
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bazarr
