apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazarr.fullname" . }}
  labels:
    {{- include "bazarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.main.type }}
  ports:
    - name: http
      port: {{ .Values.service.main.ports.http.port }}
      targetPort: 6767
      nodePort: {{ .Values.service.main.ports.http.nodePort }}
  selector:
    {{- include "bazarr.selectorLabels" . | nindent 4 }}
