apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nextcloud
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30492
