apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-postgresql
  labels:
    app: immich-postgresql
spec:
  serviceName: "immich-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgresql
  template:
    metadata:
      labels:
        app: immich-postgresql
    spec:
      containers:
        - name: postgres
          image: tensorchord/pgvecto-rs:pg16-v0.2.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: immich
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: u9FNA6p6D9
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgresql
  labels:
    app: immich-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: immich-postgresql
