apiVersion: apps/v1
kind: Deployment
metadata:
  name: readeck
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: readeck
  template:
    metadata:
      labels:
        app.kubernetes.io/name: readeck
    spec:
      containers:
        - name: readeck
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          command: ["/bin/sh", "-c", "nginx -g 'daemon off;' -c /etc/nginx/nginx.conf"]
          volumeMounts:
            - name: config
              mountPath: "{{ .Values.persistence.mountPath }}"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: "{{ .Values.persistence.existingClaim }}"
