apiVersion: apps/v1
kind: Deployment
metadata:
  name: readeck
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: readeck
  template:
    metadata:
      labels:
        app.kubernetes.io/name: readeck
    spec:
      containers:
        - name: readeck
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: readeck
              mountPath: /readeck
      volumes:
        - name: readeck
          persistentVolumeClaim:
            claimName: readeck-config
