apiVersion: apps/v1
kind: Deployment
metadata:
  name: readeck
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: readeck
  template:
    metadata:
      labels:
        app.kubernetes.io/name: readeck
    spec:
      containers:
        - name: readeck
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: watch
              mountPath: /watch
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: readeck-config
        - name: downloads
          hostPath:
            path: {{ .Values.persistence.downloads.path }}
        - name: watch
          hostPath:
            path: {{ .Values.persistence.watch.path }}
