apiVersion: v1
kind: Service
metadata:
  name: readeck
  namespace: media
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: readeck
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort | int }}
