apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission
    spec:
      containers:
        - name: transmission
          image: "linuxserver/transmission:4.0.5"
          ports:
            - containerPort: 9091
              name: http
          env:
            - name: TZ
              value: "UTC"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: watch
              mountPath: /watch
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config
        - name: downloads
          hostPath:
            path: /mnt/Father/downloads/transmission
        - name: watch
          hostPath:
            path: /mnt/Father/downloads/transmission/watch
