apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30891
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: transmission
