image:
  repository: linuxserver/bazarr
  tag: latest

service:
  main:
    type: NodePort
    ports:
      http: 6767
    nodePort: 30892

persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: bazarr-config
  movies:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/Movies
    mountPath: /movies/father
  movies2:
    enabled: true
    type: hostPath
    hostPath: /mnt/Mother/Movies
    mountPath: /movies/mother
  tv:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/TV
    mountPath: /tv/father
  tv2:
    enabled: true
    type: hostPath
    hostPath: /mnt/Mother/TV
    mountPath: /tv/mother

env:
  TZ: UTC
