image:
  repository: linuxserver/bazarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  PUID: 1000
  PGID: 100
  TZ: Europe/Berlin

service:
  main:
    enabled: true
    type: NodePort
    ports:
    - containerPort: 6767
      hostPort: 6767

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: longhorn-2replicas

  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/bazarr
    mountPath: /data

resources: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 100

nodeSelector:
  kubernetes.io/hostname: node1
