apiVersion: batch/v1
kind: Job
metadata:
  name: patch-velero-pvc
  namespace: velero
  labels:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: velero
      restartPolicy: Never
      containers:
        - name: patch-velero
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl -n velero patch deployment velero --type=json -p='[
                {
                  "op": "add",
                  "path": "/spec/template/spec/volumes/-",
                  "value": {
                    "name": "velero-backup",
                    "persistentVolumeClaim": {
                      "claimName": "velero-backup-pvc"
                    }
                  }
                },
                {
                  "op": "add",
                  "path": "/spec/template/spec/containers/0/volumeMounts/-",
                  "value": {
                    "name": "velero-backup",
                    "mountPath": "/mnt/velero"
                  }
                }
              ]'
