apiVersion: v1
kind: PersistentVolume
metadata:
  name: velero-backup-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/Mother/downloads/backups/velero
  volumeMode: Filesystem
