image:
  repository: velero/velero
  tag: v1.16.0
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Berlin

backupStorageLocation:
  name: velero-local
  provider: velero.io/kopia
  bucket: velero-local-bucket
  config:
    path: /mnt/velero

# Optional - used if you later add a VolumeSnapshotLocation
volumeSnapshotLocation:
  name: default
  provider: velero.io/noop

service:
  main:
    enabled: true
    type: NodePort
    ports:
      - port: 8085
        targetPort: 8085
        protocol: TCP
        name: http
        nodePort: 30985  # Change if needed
