apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: velero
type: Opaque
stringData:
  credentials-velero: |
    [default]
    aws_access_key_id = velero
    aws_secret_access_key = NjYxNzEyZGE1YjcwOTkzZjlhZDA4M2Y5NzU3ZDVmZTc
