apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stubby
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/flint24/k8s-apps.git
    targetRevision: HEAD
    path: stubby
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
