apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: homepage
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30410
