apiVersion: v1
kind: Service
metadata:
  name: readarr
  labels:
    app: readarr
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8787
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: readarr
