apiVersion: v1
kind: Service
metadata:
  name: readarr
spec:
  type: {{ .Values.service.main.type }}
  selector:
    app: readarr
  ports:
    - port: {{ .Values.service.main.ports.http.port }}
      targetPort: 8787
      nodePort: {{ .Values.service.main.ports.http.nodePort }}
