image:
  repository: linuxserver/transmission
  tag: latest
  pullPolicy: IfNotPresent

env:
  PUID: 1000
  PGID: 100
  TZ: Europe/Berlin

service:
  main:
    enabled: true
    type: NodePort
    ports:
      http:
        port: 9091
        nodePort: 30991

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: longhorn-2replicas

  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/transmission
    mountPath: /downloads

  watch:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/transmission/watch
    mountPath: /watch

  web:
    enabled: false  # Critical: Disable this to avoid 404 on UI

resources: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 100
  fsGroup: 100

nodeSelector:
  kubernetes.io/hostname: node1
