image:
  repository: linuxserver/transmission
  tag: 4.0.5

service:
  main:
    type: NodePort
    ports:
      http: 9091
    nodePort: 30891

persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: transmission-config
  downloads:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/transmission
    mountPath: /downloads
  watch:
    enabled: true
    type: hostPath
    hostPath: /mnt/Father/downloads/transmission/watch
    mountPath: /watch

env:
  TZ: UTC
