apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  type: NodePort
  ports:
    - port: 9696
      targetPort: 9696
      nodePort: 30894
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prowlarr
