apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cleanup-supercombo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/flint24/k8s-apps.git'
    targetRevision: main
    path: system/cleanup-supercombo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
