apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-supercombo
  namespace: media
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup-supercombo
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - |
                  kubectl get pods --all-namespaces --field-selector status.phase=Pending -o jsonpath='{range .items[*]}{.metadata.namespace} {.metadata.name}{"\n"}{end}' | while read namespace pod; do
                    echo "Deleting stuck pod $pod in namespace $namespace"
                    kubectl delete pod $pod -n $namespace --force --grace-period=0 --wait=false
                  done
          restartPolicy: OnFailure
