apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
  template:
    metadata:
      labels:
        app.kubernetes.io/name: velero
    spec:
      serviceAccountName: velero
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
        - name: velero
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /velero
            - server
          env:
            - name: TZ
              value: "{{ .Values.env.TZ }}"
