apiVersion: v1
kind: Service
metadata:
  name: velero
  labels:
    app.kubernetes.io/name: velero
spec:
  type: {{ .Values.service.main.type }}
  selector:
    app.kubernetes.io/name: velero
  ports:
    - name: http
      port: {{ .Values.service.main.ports.http.port }}
      targetPort: {{ .Values.service.main.ports.http.port }}
      nodePort: {{ .Values.service.main.ports.http.nodePort }}
