apiVersion: v1
kind: Service
metadata:
  name: velero
  labels:
    {{- include "velero.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: velero
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
